node {
    // reference to maven
    // ** NOTE: This 'maven-3.5.2' Maven tool must be configured in the Jenkins Global Configuration.   
    def mvnHome = tool 'maven-3.5.2'

    // holds reference to docker image
    def dockerImage
 
    def dockerImageTag = "pruebaweb${env.BUILD_NUMBER}"
    
    stage('Clone Repo') { // for display purposes
      // Get some code from a GitHub repository
      git 'https://github.com/felipemeriga/DevOps-Example.git'
      // Get the Maven tool.
      // ** NOTE: This 'maven-3.5.2' Maven tool must be configured
      // **       in the global configuration.           
      mvnHome = tool 'maven-3.5.2'
    }    
  
    stage('Build Project') {
      // build project via maven
      sh "'${mvnHome}/bin/mvn' clean install"
    }
		
    stage('Build Docker Image') {
      // build docker image
      dockerImage = docker.build("pruebaweb:${env.BUILD_NUMBER}")
    }
   
    stage('Deploy Docker Image'){
      
		
      echo "Docker Image Tag Name: ${dockerImageTag}"
	  
	  //sh "docker stop pruebaweb"
	  
	  //sh "docker rm pruebaweb"
	  
	  sh "docker run --name pruebaweb -d -p 8081:8081 pruebaweb:${env.BUILD_NUMBER}"
	  
      
    }
}